CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   order_id UUID NOT NULL,
   payment_method INTEGER NOT NULL,
   payment_value DECIMAL NOT NULL,
   tax DECIMAL,
   discount DECIMAL,
   status INTEGER,
   created_at date NOT NULL,
   updated_at date NOT NULL,
   customer_customer_id BIGINT,
   zip_code VARCHAR(255) NOT NULL,
   city VARCHAR(255) NOT NULL,
   street VARCHAR(255) NOT NULL,
   number VARCHAR(255) NOT NULL,
   complement VARCHAR(255) NOT NULL,
   CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE orders ADD CONSTRAINT FK_ORDERS_ON_CUSTOMER_CUSTOMERID FOREIGN KEY (customer_customer_id) REFERENCES customer (customer_id);